SET @table_name = "sars_cov_2_genes";
CALL create_basic_table(@table_name);

CALL upsert_basic_table(@table_name, "E (orf4)", 1);
CALL upsert_basic_table(@table_name, "M (orf5)", 2);
CALL upsert_basic_table(@table_name, "N (orf9)", 3);
CALL upsert_basic_table(@table_name, "spike (orf2)", 4);
CALL upsert_basic_table(@table_name, "ORF1ab (rep)", 5);
CALL upsert_basic_table(@table_name, "ORF1a (pp1a)", 6);
CALL upsert_basic_table(@table_name, "nsp11", 7);
CALL upsert_basic_table(@table_name, "nsp1", 8);
CALL upsert_basic_table(@table_name, "nsp2", 9);
CALL upsert_basic_table(@table_name, "nsp3", 10);
CALL upsert_basic_table(@table_name, "nsp4", 11);
CALL upsert_basic_table(@table_name, "nsp5", 12);
CALL upsert_basic_table(@table_name, "nsp6", 13);
CALL upsert_basic_table(@table_name, "nsp7", 14);
CALL upsert_basic_table(@table_name, "nsp8", 15);
CALL upsert_basic_table(@table_name, "nsp9", 16);
CALL upsert_basic_table(@table_name, "nsp10", 17);
CALL upsert_basic_table(@table_name, "nsp12 (RdRp)", 18);
CALL upsert_basic_table(@table_name, "nsp13 (Hel)", 19);
CALL upsert_basic_table(@table_name, "nsp14 (ExoN)", 20);
CALL upsert_basic_table(@table_name, "nsp15", 21);
CALL upsert_basic_table(@table_name, "nsp16", 22);
CALL upsert_basic_table(@table_name, "ORF3a", 23);
CALL upsert_basic_table(@table_name, "ORF3b", 24);
CALL upsert_basic_table(@table_name, "ORF6 (ns6)", 25);
CALL upsert_basic_table(@table_name, "ORF7a", 26);
CALL upsert_basic_table(@table_name, "ORF7b (ns7b)", 27);
CALL upsert_basic_table(@table_name, "ORF8 (ns8)", 28);
CALL upsert_basic_table(@table_name, "ORF9b", 29);
CALL upsert_basic_table(@table_name, "ORF9c", 30);
CALL upsert_basic_table(@table_name, "ORF10", 31);
CALL upsert_basic_table(@table_name, "ORF14", 32);
