version: "3.6"

networks:
  app-network:
    external: false

services:

  interface:

    #    image: horvathi94/seq-test
    build: ./web-interface

    depends_on:
      - database

    ports:
      - "5000:5000"

    environment:
      MYSQL_DATABASE: sequencing_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345

    volumes:
      - ./web-interface/code:/app/code

    networks:
      - app-network


  database:

    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sequencing_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345

    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/initdb:/initdb
      - ./database/backups/:/backups

    networks:
      - app-network

