version: "3.6"

networks:
  seqmeta-database:
    external: false


services:

  app:

    build:
      context: ./web-interface
      target: ${STAGING_LEVEL:-development}
      dockerfile: Dockerfile

    ports:
      - ${HOST_PORT}:5000

    depends_on:
      - database

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sequencing_data}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345}


    volumes:
      - ./web-interface/app:/home/seqmeta/app
      - ./web-interface/src:/opt/seqmeta/seqmeta
      - ${APP_SAMPLES_DIR:?Specify directory}:/home/seqmeta/uploads/samples

    networks:
      - seqmeta-database


  database:

    build:
      context: ./database
      dockerfile: Dockerfile

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sequencing_data}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-1234567890}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345}


    volumes:
      - ${MYSQL_BACKUPS_DIR:?Specify directory}:/backups
        #      - ${MYSQL_DATABASE_DIR:?Sepcify directory}:/var/lib/mysql

    networks:
      - seqmeta-database

