version: "3.6"

networks:
  app-network:
    external: false

services:

  interface:

    env_file: run.env

    build: 
      context: ./web-interface
      target: ${STAGING_LEVEL:-development}
      dockerfile: Dockerfile

    depends_on:
      - database

    ports:
      - ${PORT:-5000}:5000

    volumes:
      - ./web-interface/app:/app
      - ./uploads/samples:/uploads/samples

    networks:
      - app-network



  database:

    env_file: run.env

    build: 
     context: ./database
     dockerfile: Dockerfile

    volumes:
      - ./database/scripts:/scripts
      - ${MYSQL_BACKUPS_DIR}:/backups
      - ${MYSQL_DATABASE_DIR}:/var/lib/mysql

    networks:
      - app-network

