version: "3.6"

networks:
  seqmeta-database:
    external: false
  seqmeta-routing:
    external: false


services:

  nginx:

    image: nginx:1.20

    depends_on:
      - app

    ports:
      - ${HOST_PORT}:80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/app.conf
      - ./web-interface/app/application/static:/www/data/static/

    networks:
      - seqmeta-routing


  app:

    build:
      context: ./web-interface
      target: ${STAGING_LEVEL:-production}
      dockerfile: Dockerfile

    depends_on:
      - database

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sequencing_data}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345}


    volumes:
      - ${APP_SAMPLES_DIR:?Specify directory}:/uploads/samples

    networks:
      - seqmeta-routing
      - seqmeta-database


  database:

    image: horvathi/seqmeta-database

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sequencing_data}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-1234567890}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345}


    volumes:
      - ${MYSQL_BACKUPS_DIR:?Specify directory}:/backups
      - ${MYSQL_DATABASE_DIR:?Sepcify directory}:/var/lib/mysql

    networks:
      - seqmeta-database

