CREATE TABLE IF NOT EXISTS `authors` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	first_name VARCHAR(100) NOT NULL,
	middle_name VARCHAR(100),
	last_name VARCHAR(100) NOT NULL,

	PRIMARY KEY(id)

);


CREATE TABLE IF NOT EXISTS `author_groups` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,

	PRIMARY KEY(id)

);



CREATE TABLE IF NOT EXISTS `authors_in_group` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	order_index INT UNSIGNED NOT NULL,
	author_id INT UNSIGNED NOT NULL,
	agroup_id INT UNSIGNED NOT NULL,

	PRIMARY KEY(id),
	INDEX (order_index),

	FOREIGN KEY (author_id)
		REFERENCES authors(id)
		ON DELETE CASCADE,

	FOREIGN KEY (agroup_id)
		REFERENCES author_groups(id)
		ON DELETE CASCADE

);
