SET @table_name = "countries";
SET @view_name = "view_countries";

CALL create_basic_table(@table_name);
CALL create_basic_view(@view_name, @table_name);


CALL upsert_basic_table(@table_name, "Afghanistan", 1);
CALL upsert_basic_table(@table_name, "Albania", 2);
CALL upsert_basic_table(@table_name, "Algeria", 3);
CALL upsert_basic_table(@table_name, "American Samoa", 4);
CALL upsert_basic_table(@table_name, "Andorra", 5);
CALL upsert_basic_table(@table_name, "Angola", 6);
CALL upsert_basic_table(@table_name, "Anguilla", 7);
CALL upsert_basic_table(@table_name, "Antarctica", 8);
CALL upsert_basic_table(@table_name, "Antigua and Barbuda", 9);
CALL upsert_basic_table(@table_name, "Arctic Ocean", 10);
CALL upsert_basic_table(@table_name, "Argentina", 11);
CALL upsert_basic_table(@table_name, "Armenia", 12);
CALL upsert_basic_table(@table_name, "Aruba", 13);
CALL upsert_basic_table(@table_name, "Ashmore and Cartier Islands", 14);
CALL upsert_basic_table(@table_name, "Atlantic Ocean", 15);
CALL upsert_basic_table(@table_name, "Australia", 16);
CALL upsert_basic_table(@table_name, "Austria", 17);
CALL upsert_basic_table(@table_name, "Azerbaijan", 18);
CALL upsert_basic_table(@table_name, "Bahamas", 19);
CALL upsert_basic_table(@table_name, "Bahrain", 20);
CALL upsert_basic_table(@table_name, "Baltic Sea", 21);
CALL upsert_basic_table(@table_name, "Baker Island", 22);
CALL upsert_basic_table(@table_name, "Bangladesh", 23);
CALL upsert_basic_table(@table_name, "Barbados", 24);
CALL upsert_basic_table(@table_name, "Bassas da India", 25);
CALL upsert_basic_table(@table_name, "Belarus", 26);
CALL upsert_basic_table(@table_name, "Belgium", 27);
CALL upsert_basic_table(@table_name, "Belize", 28);
CALL upsert_basic_table(@table_name, "Benin", 29);
CALL upsert_basic_table(@table_name, "Bermuda", 30);
CALL upsert_basic_table(@table_name, "Bhutan", 31);
CALL upsert_basic_table(@table_name, "Bolivia", 32);
CALL upsert_basic_table(@table_name, "Borneo", 33);
CALL upsert_basic_table(@table_name, "Bosnia and Herzegovina", 34);
CALL upsert_basic_table(@table_name, "Botswana", 35);
CALL upsert_basic_table(@table_name, "Bouvet Island", 36);
CALL upsert_basic_table(@table_name, "Brazil", 37);
CALL upsert_basic_table(@table_name, "British Virgin Islands", 38);
CALL upsert_basic_table(@table_name, "Brunei", 39);
CALL upsert_basic_table(@table_name, "Bulgaria", 40);
CALL upsert_basic_table(@table_name, "Burkina Faso", 41);
CALL upsert_basic_table(@table_name, "Burundi", 42);
CALL upsert_basic_table(@table_name, "Cambodia", 43);
CALL upsert_basic_table(@table_name, "Cameroon", 44);
CALL upsert_basic_table(@table_name, "Canada", 45);
CALL upsert_basic_table(@table_name, "Cape Verde", 46);
CALL upsert_basic_table(@table_name, "Cayman Islands", 47);
CALL upsert_basic_table(@table_name, "Central African Republic", 48);
CALL upsert_basic_table(@table_name, "Chad", 49);
CALL upsert_basic_table(@table_name, "Chile", 50);
CALL upsert_basic_table(@table_name, "China", 51);
CALL upsert_basic_table(@table_name, "Christmas Island", 52);
CALL upsert_basic_table(@table_name, "Clipperton Island", 53);
CALL upsert_basic_table(@table_name, "Cocos Islands", 54);
CALL upsert_basic_table(@table_name, "Colombia", 55);
CALL upsert_basic_table(@table_name, "Comoros", 56);
CALL upsert_basic_table(@table_name, "Cook Islands", 57);
CALL upsert_basic_table(@table_name, "Coral Sea Islands", 58);
CALL upsert_basic_table(@table_name, "Costa Rica", 59);
CALL upsert_basic_table(@table_name, "Cote d`Ivoire", 60);
CALL upsert_basic_table(@table_name, "Croatia", 61);
CALL upsert_basic_table(@table_name, "Cuba", 62);
CALL upsert_basic_table(@table_name, "Curacao", 63);
CALL upsert_basic_table(@table_name, "Cyprus", 64);
CALL upsert_basic_table(@table_name, "Czech Republic", 65);
CALL upsert_basic_table(@table_name, "Democratic Republic of the Congo", 66);
CALL upsert_basic_table(@table_name, "Denmark", 67);
CALL upsert_basic_table(@table_name, "Djibouti", 68);
CALL upsert_basic_table(@table_name, "Dominica", 69);
CALL upsert_basic_table(@table_name, "Dominican Republic", 70);
CALL upsert_basic_table(@table_name, "Ecuador", 71);
CALL upsert_basic_table(@table_name, "Egypt", 72);
CALL upsert_basic_table(@table_name, "El Salvador", 73);
CALL upsert_basic_table(@table_name, "Equatorial Guinea", 74);
CALL upsert_basic_table(@table_name, "Eritrea", 75);
CALL upsert_basic_table(@table_name, "Estonia", 76);
CALL upsert_basic_table(@table_name, "Eswatini", 77);
CALL upsert_basic_table(@table_name, "Ethiopia", 78);
CALL upsert_basic_table(@table_name, "Europa Island", 79);
CALL upsert_basic_table(@table_name, "Falkland Islands (Islas Malvinas)", 80);
CALL upsert_basic_table(@table_name, "Faroe Islands", 81);
CALL upsert_basic_table(@table_name, "Fiji", 82);
CALL upsert_basic_table(@table_name, "Finland", 83);
CALL upsert_basic_table(@table_name, "France", 84);
CALL upsert_basic_table(@table_name, "French Guiana", 85);
CALL upsert_basic_table(@table_name, "French Polynesia", 86);
CALL upsert_basic_table(@table_name, "French Southern and Antarctic Lands", 87);
CALL upsert_basic_table(@table_name, "Gabon", 88);
CALL upsert_basic_table(@table_name, "Gambia", 89);
CALL upsert_basic_table(@table_name, "Gaza Strip", 90);
CALL upsert_basic_table(@table_name, "Georgia", 91);
CALL upsert_basic_table(@table_name, "Germany", 92);
CALL upsert_basic_table(@table_name, "Ghana", 93);
CALL upsert_basic_table(@table_name, "Gibraltar", 94);
CALL upsert_basic_table(@table_name, "Glorioso Islands", 95);
CALL upsert_basic_table(@table_name, "Greece", 96);
CALL upsert_basic_table(@table_name, "Greenland", 97);
CALL upsert_basic_table(@table_name, "Grenada", 98);
CALL upsert_basic_table(@table_name, "Guadeloupe", 99);
CALL upsert_basic_table(@table_name, "Guam", 100);
CALL upsert_basic_table(@table_name, "Guatemala", 101);
CALL upsert_basic_table(@table_name, "Guernsey", 102);
CALL upsert_basic_table(@table_name, "Guinea", 103);
CALL upsert_basic_table(@table_name, "Guinea-Bissau", 104);
CALL upsert_basic_table(@table_name, "Guyana", 105);
CALL upsert_basic_table(@table_name, "Haiti", 106);
CALL upsert_basic_table(@table_name, "Heard Island and McDonald Islands", 107);
CALL upsert_basic_table(@table_name, "Honduras", 108);
CALL upsert_basic_table(@table_name, "Hong Kong", 109);
CALL upsert_basic_table(@table_name, "Howland Island", 110);
CALL upsert_basic_table(@table_name, "Hungary", 111);
CALL upsert_basic_table(@table_name, "Iceland", 112);
CALL upsert_basic_table(@table_name, "India", 113);
CALL upsert_basic_table(@table_name, "Indian Ocean", 114);
CALL upsert_basic_table(@table_name, "Indonesia", 115);
CALL upsert_basic_table(@table_name, "Iran", 116);
CALL upsert_basic_table(@table_name, "Iraq", 117);
CALL upsert_basic_table(@table_name, "Ireland", 118);
CALL upsert_basic_table(@table_name, "Isle of Man", 119);
CALL upsert_basic_table(@table_name, "Israel", 120);
CALL upsert_basic_table(@table_name, "Italy", 121);
CALL upsert_basic_table(@table_name, "Jamaica", 122);
CALL upsert_basic_table(@table_name, "Jan Mayen", 123);
CALL upsert_basic_table(@table_name, "Japan", 124);
CALL upsert_basic_table(@table_name, "Jarvis Island", 125);
CALL upsert_basic_table(@table_name, "Jersey", 126);
CALL upsert_basic_table(@table_name, "Johnston Atoll", 127);
CALL upsert_basic_table(@table_name, "Jordan", 128);
CALL upsert_basic_table(@table_name, "Juan de Nova Island", 129);
CALL upsert_basic_table(@table_name, "Kazakhstan", 130);
CALL upsert_basic_table(@table_name, "Kenya", 131);
CALL upsert_basic_table(@table_name, "Kerguelen Archipelago", 132);
CALL upsert_basic_table(@table_name, "Kingman Reef", 133);
CALL upsert_basic_table(@table_name, "Kiribati", 134);
CALL upsert_basic_table(@table_name, "Kosovo", 135);
CALL upsert_basic_table(@table_name, "Kuwait", 136);
CALL upsert_basic_table(@table_name, "Kyrgyzstan", 137);
CALL upsert_basic_table(@table_name, "Laos", 138);
CALL upsert_basic_table(@table_name, "Latvia", 139);
CALL upsert_basic_table(@table_name, "Lebanon", 140);
CALL upsert_basic_table(@table_name, "Lesotho", 141);
CALL upsert_basic_table(@table_name, "Liberia", 142);
CALL upsert_basic_table(@table_name, "Libya", 143);
CALL upsert_basic_table(@table_name, "Liechtenstein", 144);
CALL upsert_basic_table(@table_name, "Line Islands", 145);
CALL upsert_basic_table(@table_name, "Lithuania", 146);
CALL upsert_basic_table(@table_name, "Luxembourg", 147);
CALL upsert_basic_table(@table_name, "Macau", 148);
CALL upsert_basic_table(@table_name, "Madagascar", 149);
CALL upsert_basic_table(@table_name, "Malawi", 150);
CALL upsert_basic_table(@table_name, "Malaysia", 151);
CALL upsert_basic_table(@table_name, "Maldives", 152);
CALL upsert_basic_table(@table_name, "Mali", 153);
CALL upsert_basic_table(@table_name, "Malta", 154);
CALL upsert_basic_table(@table_name, "Marshall Islands", 155);
CALL upsert_basic_table(@table_name, "Martinique", 156);
CALL upsert_basic_table(@table_name, "Mauritania", 157);
CALL upsert_basic_table(@table_name, "Mauritius", 158);
CALL upsert_basic_table(@table_name, "Mayotte", 159);
CALL upsert_basic_table(@table_name, "Mediterranean Sea", 160);
CALL upsert_basic_table(@table_name, "Mexico", 161);
CALL upsert_basic_table(@table_name, "Micronesia", 162);
CALL upsert_basic_table(@table_name, "Midway Islands", 163);
CALL upsert_basic_table(@table_name, "Moldova", 164);
CALL upsert_basic_table(@table_name, "Monaco", 165);
CALL upsert_basic_table(@table_name, "Mongolia", 166);
CALL upsert_basic_table(@table_name, "Montenegro", 167);
CALL upsert_basic_table(@table_name, "Montserrat", 168);
CALL upsert_basic_table(@table_name, "Morocco", 169);
CALL upsert_basic_table(@table_name, "Mozambique", 170);
CALL upsert_basic_table(@table_name, "Myanmar", 171);
CALL upsert_basic_table(@table_name, "Namibia", 172);
CALL upsert_basic_table(@table_name, "Nauru", 173);
CALL upsert_basic_table(@table_name, "Navassa Island", 174);
CALL upsert_basic_table(@table_name, "Nepal", 175);
CALL upsert_basic_table(@table_name, "Netherlands", 176);
CALL upsert_basic_table(@table_name, "New Caledonia", 177);
CALL upsert_basic_table(@table_name, "New Zealand", 178);
CALL upsert_basic_table(@table_name, "Nicaragua", 179);
CALL upsert_basic_table(@table_name, "Niger", 180);
CALL upsert_basic_table(@table_name, "Nigeria", 181);
CALL upsert_basic_table(@table_name, "Niue", 182);
CALL upsert_basic_table(@table_name, "Norfolk Island", 183);
CALL upsert_basic_table(@table_name, "North Korea", 184);
CALL upsert_basic_table(@table_name, "North Macedonia", 185);
CALL upsert_basic_table(@table_name, "North Sea", 186);
CALL upsert_basic_table(@table_name, "Northern Mariana Islands", 187);
CALL upsert_basic_table(@table_name, "Norway", 188);
CALL upsert_basic_table(@table_name, "Oman", 189);
CALL upsert_basic_table(@table_name, "Pacific Ocean", 190);
CALL upsert_basic_table(@table_name, "Pakistan", 191);
CALL upsert_basic_table(@table_name, "Palau", 192);
CALL upsert_basic_table(@table_name, "Palmyra Atoll", 193);
CALL upsert_basic_table(@table_name, "Panama", 194);
CALL upsert_basic_table(@table_name, "Papua New Guinea", 195);
CALL upsert_basic_table(@table_name, "Paracel Islands", 196);
CALL upsert_basic_table(@table_name, "Paraguay", 197);
CALL upsert_basic_table(@table_name, "Peru", 198);
CALL upsert_basic_table(@table_name, "Philippines", 199);
CALL upsert_basic_table(@table_name, "Pitcairn Islands", 200);
CALL upsert_basic_table(@table_name, "Poland", 201);
CALL upsert_basic_table(@table_name, "Portugal", 202);
CALL upsert_basic_table(@table_name, "Puerto Rico", 203);
CALL upsert_basic_table(@table_name, "Qatar", 204);
CALL upsert_basic_table(@table_name, "Republic of the Congo", 205);
CALL upsert_basic_table(@table_name, "Reunion", 206);
CALL upsert_basic_table(@table_name, "Romania", 207);
CALL upsert_basic_table(@table_name, "Ross Sea", 208);
CALL upsert_basic_table(@table_name, "Russia", 209);
CALL upsert_basic_table(@table_name, "Rwanda", 210);
CALL upsert_basic_table(@table_name, "Saint Helena", 211);
CALL upsert_basic_table(@table_name, "Saint Kitts and Nevis", 212);
CALL upsert_basic_table(@table_name, "Saint Lucia", 213);
CALL upsert_basic_table(@table_name, "Saint Pierre and Miquelon", 214);
CALL upsert_basic_table(@table_name, "Saint Vincent and the Grenadines", 215);
CALL upsert_basic_table(@table_name, "Samoa", 216);
CALL upsert_basic_table(@table_name, "San Marino", 217);
CALL upsert_basic_table(@table_name, "Sao Tome and Principe", 218);
CALL upsert_basic_table(@table_name, "Saudi Arabia", 219);
CALL upsert_basic_table(@table_name, "Senegal", 220);
CALL upsert_basic_table(@table_name, "Serbia", 221);
CALL upsert_basic_table(@table_name, "Seychelles", 222);
CALL upsert_basic_table(@table_name, "Sierra Leone", 223);
CALL upsert_basic_table(@table_name, "Singapore", 224);
CALL upsert_basic_table(@table_name, "Sint Maarten", 225);
CALL upsert_basic_table(@table_name, "Slovakia", 226);
CALL upsert_basic_table(@table_name, "Slovenia", 227);
CALL upsert_basic_table(@table_name, "Solomon Islands", 228);
CALL upsert_basic_table(@table_name, "Somalia", 229);
CALL upsert_basic_table(@table_name, "South Africa", 230);
CALL upsert_basic_table(@table_name, "South Georgia and the South Sandwich Islands", 231);
CALL upsert_basic_table(@table_name, "South Korea", 232);
CALL upsert_basic_table(@table_name, "South Sudan", 233);
CALL upsert_basic_table(@table_name, "Southern Ocean", 234);
CALL upsert_basic_table(@table_name, "Spain", 235);
CALL upsert_basic_table(@table_name, "Spratly Islands", 236);
CALL upsert_basic_table(@table_name, "Sri Lanka", 237);
CALL upsert_basic_table(@table_name, "State of Palestine", 238);
CALL upsert_basic_table(@table_name, "Sudan", 239);
CALL upsert_basic_table(@table_name, "Suriname", 240);
CALL upsert_basic_table(@table_name, "Svalbard", 241);
CALL upsert_basic_table(@table_name, "Sweden", 242);
CALL upsert_basic_table(@table_name, "Switzerland", 243);
CALL upsert_basic_table(@table_name, "Syria", 244);
CALL upsert_basic_table(@table_name, "Taiwan", 245);
CALL upsert_basic_table(@table_name, "Tajikistan", 246);
CALL upsert_basic_table(@table_name, "Tanzania", 247);
CALL upsert_basic_table(@table_name, "Tasman Sea", 248);
CALL upsert_basic_table(@table_name, "Thailand", 249);
CALL upsert_basic_table(@table_name, "Timor-Leste", 250);
CALL upsert_basic_table(@table_name, "Togo", 251);
CALL upsert_basic_table(@table_name, "Tokelau", 252);
CALL upsert_basic_table(@table_name, "Tonga", 253);
CALL upsert_basic_table(@table_name, "Trinidad and Tobago", 254);
CALL upsert_basic_table(@table_name, "Tromelin Island", 255);
CALL upsert_basic_table(@table_name, "Tunisia", 256);
CALL upsert_basic_table(@table_name, "Turkey", 257);
CALL upsert_basic_table(@table_name, "Turkmenistan", 258);
CALL upsert_basic_table(@table_name, "Turks and Caicos Islands", 259);
CALL upsert_basic_table(@table_name, "Tuvalu", 260);
CALL upsert_basic_table(@table_name, "USA", 261);
CALL upsert_basic_table(@table_name, "Uganda", 262);
CALL upsert_basic_table(@table_name, "Ukraine", 263);
CALL upsert_basic_table(@table_name, "United Arab Emirates", 264);
CALL upsert_basic_table(@table_name, "United Kingdom", 265);
CALL upsert_basic_table(@table_name, "Uruguay", 266);
CALL upsert_basic_table(@table_name, "Uzbekistan", 267);
CALL upsert_basic_table(@table_name, "Vanuatu", 268);
CALL upsert_basic_table(@table_name, "Venezuela", 269);
CALL upsert_basic_table(@table_name, "Viet Nam", 270);
CALL upsert_basic_table(@table_name, "Virgin Islands", 271);
CALL upsert_basic_table(@table_name, "Wake Island", 272);
CALL upsert_basic_table(@table_name, "Wallis and Futuna", 273);
CALL upsert_basic_table(@table_name, "West Bank", 274);
CALL upsert_basic_table(@table_name, "Western Sahara", 275);
CALL upsert_basic_table(@table_name, "Yemen", 276);
CALL upsert_basic_table(@table_name, "Zambia", 277);
CALL upsert_basic_table(@table_name, "Zimbabwe", 278);
