CALL create_dict_table("library_strategies");
CALL create_dict_table("library_sources");
CALL create_dict_table("library_selections");

CALL upsert_dict_table("library_strategies", 1, "WGA", "Random sequencing of the whole genome following non-pcr amplification");
CALL upsert_dict_table("library_strategies", 2, "WGS", "Random sequencing of the whole genome");
CALL upsert_dict_table("library_strategies", 3, "WXS", "Random sequencing of exonic regions selected from the genome");
CALL upsert_dict_table("library_strategies", 4, "RNA-Seq", "Random sequencing of whole transcriptome");
CALL upsert_dict_table("library_strategies", 5, "miRNA-Seq", "Random sequencing of small miRNAs");
CALL upsert_dict_table("library_strategies", 6, "WCS", "Random sequencing of a whole chromosome or other replicon isolated from a genome");
CALL upsert_dict_table("library_strategies", 7, "CLONE", "Genomic clone based (hierarchical) sequencing");
CALL upsert_dict_table("library_strategies", 8, "POOLCLONE", "Shotgun of pooled clones (usually BACs and Fosmids)");
CALL upsert_dict_table("library_strategies", 9, "AMPLICON", "Sequencing of overlapping or distinct PCR or RT-PCR products");
CALL upsert_dict_table("library_strategies", 10, "CLONEEND", "Clone end (5`, 3`, or both) sequencing");
CALL upsert_dict_table("library_strategies", 11, "FINISHING", "Sequencing intended to finish (close) gaps in existing coverage");
CALL upsert_dict_table("library_strategies", 12, "ChIP-Seq", "Direct sequencing of chromatin immunoprecipitates");
CALL upsert_dict_table("library_strategies", 13, "MNase-Seq", "Direct sequencing following MNase digestion");
CALL upsert_dict_table("library_strategies", 14, "DNase-Hypersensitivity", "Sequencing of hypersensitive sites, or segments of open chromatin that are more readily cleaved by DNaseI");
CALL upsert_dict_table("library_strategies", 15, "Bisulfite-Seq", "Sequencing following treatment of DNA with bisulfite to convert cytosine residues to uracil depending on methylation status");
CALL upsert_dict_table("library_strategies", 16, "Tn-Seq", "Sequencing from transposon insertion sites");
CALL upsert_dict_table("library_strategies", 17, "EST", "Single pass sequencing of cDNA templates");
CALL upsert_dict_table("library_strategies", 18, "FL-cDNA", "Full-length sequencing of cDNA templates");
CALL upsert_dict_table("library_strategies", 19, "CTS", "Concatenated Tag Sequencing");
CALL upsert_dict_table("library_strategies", 20, "MRE-Seq", "Methylation-Sensitive Restriction Enzyme Sequencing strategy");
CALL upsert_dict_table("library_strategies", 21, "MeDIP-Seq", "Methylated DNA Immunoprecipitation Sequencing strategy");
CALL upsert_dict_table("library_strategies", 22, "MBD-Seq", "Direct sequencing of methylated fractions sequencing strategy");
CALL upsert_dict_table("library_strategies", 23, "Synthetic-Long-Read", "");
CALL upsert_dict_table("library_strategies", 24, "ATAC-seq", "Assay for Transposase-Accessible Chromatin (ATAC) strategy is used to study genome-wide chromatin accessibility. alternative method to DNase-seq that uses an engineered Tn5 transposase to cleave DNA and to integrate primer DNA sequences into the cleaved genomic DNA");
CALL upsert_dict_table("library_strategies", 25, "ChIA-PET", "Direct sequencing of proximity-ligated chromatin immunoprecipitates.");
CALL upsert_dict_table("library_strategies", 26, "FAIRE-seq", "Formaldehyde Assisted Isolation of Regulatory Elements. reveals regions of open chromatin");
CALL upsert_dict_table("library_strategies", 27, "Hi-C", "Chromosome Conformation Capture technique where a biotin-labeled nucleotide is incorporated at the ligation junction, enabling selective purification of chimeric DNA ligation junctions followed by deep sequencing");
CALL upsert_dict_table("library_strategies", 28, "ncRNA-Seq", "Capture of other non-coding RNA types, including post-translation modification types such as snRNA (small nuclear RNA) or snoRNA (small nucleolar RNA), or expression regulation types such as siRNA (small interfering RNA) or piRNA/piwi/RNA (piwi-interacting RNA).");
CALL upsert_dict_table("library_strategies", 29, "RAD-Seq", "");
CALL upsert_dict_table("library_strategies", 30, "RIP-Seq", "Direct sequencing of RNA immunoprecipitates (includes CLIP-Seq, HITS-CLIP and PAR-CLIP).");
CALL upsert_dict_table("library_strategies", 31, "SELEX", "Systematic Evolution of Ligands by EXponential enrichment");
CALL upsert_dict_table("library_strategies", 32, "ssRNA-seq", "strand-specific RNA sequencing");
CALL upsert_dict_table("library_strategies", 33, "Targeted-Capture", "");
CALL upsert_dict_table("library_strategies", 34, "Tethered Chromatin Conformation Capture", "");
CALL upsert_dict_table("library_strategies", 35, "OTHER", "Library strategy not listed (please include additional info in the ` description`)");


CALL upsert_dict_table("library_selections", 1, "RANDOM", "Random selection by shearing or other method");
CALL upsert_dict_table("library_selections", 2, "PCR", "Source material was selected by designed primers");
CALL upsert_dict_table("library_selections", 3, "RANDOM PCR", "Source material was selected by randomly generated primers");
CALL upsert_dict_table("library_selections", 4, "RT-PCR", "Source material was selected by reverse transcription PCR");
CALL upsert_dict_table("library_selections", 5, "HMPR", "Hypo-methylated partial restriction digest");
CALL upsert_dict_table("library_selections", 6, "MF", "Methyl Filtrated");
CALL upsert_dict_table("library_selections", 7, "CF-S", "Cot-filtered single/low-copy genomic DNA");
CALL upsert_dict_table("library_selections", 8, "CF-M", "Cot-filtered moderately repetitive genomic DNA");
CALL upsert_dict_table("library_selections", 9, "CF-H", "Cot-filtered highly repetitive genomic DNA");
CALL upsert_dict_table("library_selections", 10, "CF-T", "Cot-filtered theoretical single-copy genomic DNA");
CALL upsert_dict_table("library_selections", 11, "MDA", "Multiple displacement amplification");
CALL upsert_dict_table("library_selections", 12, "MSLL", "Methylation Spanning Linking Library");
CALL upsert_dict_table("library_selections", 13, "cDNA", "complementary DNA");
CALL upsert_dict_table("library_selections", 14, "ChIP", "Chromatin immunoprecipitation");
CALL upsert_dict_table("library_selections", 15, "MNase", "Micrococcal Nuclease (MNase) digestion");
CALL upsert_dict_table("library_selections", 16, "DNAse", "Deoxyribonuclease (MNase) digestion");
CALL upsert_dict_table("library_selections", 17, "Hybrid Selection", "Selection by hybridization in array or solution");
CALL upsert_dict_table("library_selections", 18, "Reduced Representation", "Reproducible genomic subsets, often generated by restriction fragment size selection, containing a manageable number of loci to facilitate re-sampling");
CALL upsert_dict_table("library_selections", 19, "Restriction Digest", "DNA fractionation using restriction enzymes");
CALL upsert_dict_table("library_selections", 20, "5-methylcytidine antibody", "Selection of methylated DNA fragments using an antibody raised against 5-methylcytosine or 5-methylcytidine (m5C)");
CALL upsert_dict_table("library_selections", 21, "MBD2 protein methyl-CpG binding domain", "Enrichment by methyl-CpG binding domain");
CALL upsert_dict_table("library_selections", 22, "CAGE", "Cap-analysis gene expression");
CALL upsert_dict_table("library_selections", 23, "RACE", "Rapid Amplification of cDNA Ends");
CALL upsert_dict_table("library_selections", 24, "size fractionation", "Physical selection of size appropriate targets");
CALL upsert_dict_table("library_selections", 25, "Padlock probes capture method", "Circularized oligonucleotide probes");
CALL upsert_dict_table("library_selections", 26, "other", "Other library enrichment, screening, or selection process (please include additional info in the `design description`)");
CALL upsert_dict_table("library_selections", 27, "unspecified", "Library enrichment, screening, or selection is not specified (please include additional info in the `design description`)");
CALL upsert_dict_table("library_selections", 28, "cDNA_oligo_dT", "");
CALL upsert_dict_table("library_selections", 29, "cDNA_randomPriming", "");
CALL upsert_dict_table("library_selections", 30, "Inverse rRNA", "depletion of ribosomal RNA by oligo hybridization.");
CALL upsert_dict_table("library_selections", 31, "Oligo-dT", "enrichment of messenger RNA (mRNA) by hybridization to Oligo-dT.");
CALL upsert_dict_table("library_selections", 32, "PolyA", "PolyA selection or enrichment for messenger RNA (mRNA); should replace cDNA enumeration.");
CALL upsert_dict_table("library_selections", 33, "repeat fractionation", "Selection for less repetitive (and more gene rich) sequence through Cot filtration (CF) or other fractionation techniques based on DNA kinetics.");


CALL upsert_dict_table("library_sources", 1, "GENOMIC", "Genomic DNA (includes PCR products from genomic DNA)");
CALL upsert_dict_table("library_sources", 2, "TRANSCRIPTOMIC", "Transcription products or non genomic DNA (EST, cDNA, RT-PCR, screened libraries)");
CALL upsert_dict_table("library_sources", 3, "METAGENOMIC", "Mixed material from metagenome");
CALL upsert_dict_table("library_sources", 4, "METATRANSCRIPTOMIC", "Transcription products from community targets");
CALL upsert_dict_table("library_sources", 5, "SYNTHETIC", "Synthetic DNA");
CALL upsert_dict_table("library_sources", 6, "VIRAL RNA", "Viral RNA");
CALL upsert_dict_table("library_sources", 7, "GENOMIC SINGLE CELL", "");
CALL upsert_dict_table("library_sources", 8, "TRANSCRIPTOMIC SINGLE CELL", "");
CALL upsert_dict_table("library_sources", 9, "OTHER", "Other, unspecified, or unknown library source material (please include additional info in the `design description`)");
