CALL upsert_basic_table("countries", "Afghanistan", 1);
CALL upsert_basic_table("countries", "Albania", 2);
CALL upsert_basic_table("countries", "Algeria", 3);
CALL upsert_basic_table("countries", "American Samoa", 4);
CALL upsert_basic_table("countries", "Andorra", 5);
CALL upsert_basic_table("countries", "Angola", 6);
CALL upsert_basic_table("countries", "Anguilla", 7);
CALL upsert_basic_table("countries", "Antarctica", 8);
CALL upsert_basic_table("countries", "Antigua and Barbuda", 9);
CALL upsert_basic_table("countries", "Arctic Ocean", 10);
CALL upsert_basic_table("countries", "Argentina", 11);
CALL upsert_basic_table("countries", "Armenia", 12);
CALL upsert_basic_table("countries", "Aruba", 13);
CALL upsert_basic_table("countries", "Ashmore and Cartier Islands", 14);
CALL upsert_basic_table("countries", "Atlantic Ocean", 15);
CALL upsert_basic_table("countries", "Australia", 16);
CALL upsert_basic_table("countries", "Austria", 17);
CALL upsert_basic_table("countries", "Azerbaijan", 18);
CALL upsert_basic_table("countries", "Bahamas", 19);
CALL upsert_basic_table("countries", "Bahrain", 20);
CALL upsert_basic_table("countries", "Baltic Sea", 21);
CALL upsert_basic_table("countries", "Baker Island", 22);
CALL upsert_basic_table("countries", "Bangladesh", 23);
CALL upsert_basic_table("countries", "Barbados", 24);
CALL upsert_basic_table("countries", "Bassas da India", 25);
CALL upsert_basic_table("countries", "Belarus", 26);
CALL upsert_basic_table("countries", "Belgium", 27);
CALL upsert_basic_table("countries", "Belize", 28);
CALL upsert_basic_table("countries", "Benin", 29);
CALL upsert_basic_table("countries", "Bermuda", 30);
CALL upsert_basic_table("countries", "Bhutan", 31);
CALL upsert_basic_table("countries", "Bolivia", 32);
CALL upsert_basic_table("countries", "Borneo", 33);
CALL upsert_basic_table("countries", "Bosnia and Herzegovina", 34);
CALL upsert_basic_table("countries", "Botswana", 35);
CALL upsert_basic_table("countries", "Bouvet Island", 36);
CALL upsert_basic_table("countries", "Brazil", 37);
CALL upsert_basic_table("countries", "British Virgin Islands", 38);
CALL upsert_basic_table("countries", "Brunei", 39);
CALL upsert_basic_table("countries", "Bulgaria", 40);
CALL upsert_basic_table("countries", "Burkina Faso", 41);
CALL upsert_basic_table("countries", "Burundi", 42);
CALL upsert_basic_table("countries", "Cambodia", 43);
CALL upsert_basic_table("countries", "Cameroon", 44);
CALL upsert_basic_table("countries", "Canada", 45);
CALL upsert_basic_table("countries", "Cape Verde", 46);
CALL upsert_basic_table("countries", "Cayman Islands", 47);
CALL upsert_basic_table("countries", "Central African Republic", 48);
CALL upsert_basic_table("countries", "Chad", 49);
CALL upsert_basic_table("countries", "Chile", 50);
CALL upsert_basic_table("countries", "China", 51);
CALL upsert_basic_table("countries", "Christmas Island", 52);
CALL upsert_basic_table("countries", "Clipperton Island", 53);
CALL upsert_basic_table("countries", "Cocos Islands", 54);
CALL upsert_basic_table("countries", "Colombia", 55);
CALL upsert_basic_table("countries", "Comoros", 56);
CALL upsert_basic_table("countries", "Cook Islands", 57);
CALL upsert_basic_table("countries", "Coral Sea Islands", 58);
CALL upsert_basic_table("countries", "Costa Rica", 59);
CALL upsert_basic_table("countries", "Cote d`Ivoire", 60);
CALL upsert_basic_table("countries", "Croatia", 61);
CALL upsert_basic_table("countries", "Cuba", 62);
CALL upsert_basic_table("countries", "Curacao", 63);
CALL upsert_basic_table("countries", "Cyprus", 64);
CALL upsert_basic_table("countries", "Czech Republic", 65);
CALL upsert_basic_table("countries", "Democratic Republic of the Congo", 66);
CALL upsert_basic_table("countries", "Denmark", 67);
CALL upsert_basic_table("countries", "Djibouti", 68);
CALL upsert_basic_table("countries", "Dominica", 69);
CALL upsert_basic_table("countries", "Dominican Republic", 70);
CALL upsert_basic_table("countries", "Ecuador", 71);
CALL upsert_basic_table("countries", "Egypt", 72);
CALL upsert_basic_table("countries", "El Salvador", 73);
CALL upsert_basic_table("countries", "Equatorial Guinea", 74);
CALL upsert_basic_table("countries", "Eritrea", 75);
CALL upsert_basic_table("countries", "Estonia", 76);
CALL upsert_basic_table("countries", "Eswatini", 77);
CALL upsert_basic_table("countries", "Ethiopia", 78);
CALL upsert_basic_table("countries", "Europa Island", 79);
CALL upsert_basic_table("countries", "Falkland Islands (Islas Malvinas)", 80);
CALL upsert_basic_table("countries", "Faroe Islands", 81);
CALL upsert_basic_table("countries", "Fiji", 82);
CALL upsert_basic_table("countries", "Finland", 83);
CALL upsert_basic_table("countries", "France", 84);
CALL upsert_basic_table("countries", "French Guiana", 85);
CALL upsert_basic_table("countries", "French Polynesia", 86);
CALL upsert_basic_table("countries", "French Southern and Antarctic Lands", 87);
CALL upsert_basic_table("countries", "Gabon", 88);
CALL upsert_basic_table("countries", "Gambia", 89);
CALL upsert_basic_table("countries", "Gaza Strip", 90);
CALL upsert_basic_table("countries", "Georgia", 91);
CALL upsert_basic_table("countries", "Germany", 92);
CALL upsert_basic_table("countries", "Ghana", 93);
CALL upsert_basic_table("countries", "Gibraltar", 94);
CALL upsert_basic_table("countries", "Glorioso Islands", 95);
CALL upsert_basic_table("countries", "Greece", 96);
CALL upsert_basic_table("countries", "Greenland", 97);
CALL upsert_basic_table("countries", "Grenada", 98);
CALL upsert_basic_table("countries", "Guadeloupe", 99);
CALL upsert_basic_table("countries", "Guam", 100);
CALL upsert_basic_table("countries", "Guatemala", 101);
CALL upsert_basic_table("countries", "Guernsey", 102);
CALL upsert_basic_table("countries", "Guinea", 103);
CALL upsert_basic_table("countries", "Guinea-Bissau", 104);
CALL upsert_basic_table("countries", "Guyana", 105);
CALL upsert_basic_table("countries", "Haiti", 106);
CALL upsert_basic_table("countries", "Heard Island and McDonald Islands", 107);
CALL upsert_basic_table("countries", "Honduras", 108);
CALL upsert_basic_table("countries", "Hong Kong", 109);
CALL upsert_basic_table("countries", "Howland Island", 110);
CALL upsert_basic_table("countries", "Hungary", 111);
CALL upsert_basic_table("countries", "Iceland", 112);
CALL upsert_basic_table("countries", "India", 113);
CALL upsert_basic_table("countries", "Indian Ocean", 114);
CALL upsert_basic_table("countries", "Indonesia", 115);
CALL upsert_basic_table("countries", "Iran", 116);
CALL upsert_basic_table("countries", "Iraq", 117);
CALL upsert_basic_table("countries", "Ireland", 118);
CALL upsert_basic_table("countries", "Isle of Man", 119);
CALL upsert_basic_table("countries", "Israel", 120);
CALL upsert_basic_table("countries", "Italy", 121);
CALL upsert_basic_table("countries", "Jamaica", 122);
CALL upsert_basic_table("countries", "Jan Mayen", 123);
CALL upsert_basic_table("countries", "Japan", 124);
CALL upsert_basic_table("countries", "Jarvis Island", 125);
CALL upsert_basic_table("countries", "Jersey", 126);
CALL upsert_basic_table("countries", "Johnston Atoll", 127);
CALL upsert_basic_table("countries", "Jordan", 128);
CALL upsert_basic_table("countries", "Juan de Nova Island", 129);
CALL upsert_basic_table("countries", "Kazakhstan", 130);
CALL upsert_basic_table("countries", "Kenya", 131);
CALL upsert_basic_table("countries", "Kerguelen Archipelago", 132);
CALL upsert_basic_table("countries", "Kingman Reef", 133);
CALL upsert_basic_table("countries", "Kiribati", 134);
CALL upsert_basic_table("countries", "Kosovo", 135);
CALL upsert_basic_table("countries", "Kuwait", 136);
CALL upsert_basic_table("countries", "Kyrgyzstan", 137);
CALL upsert_basic_table("countries", "Laos", 138);
CALL upsert_basic_table("countries", "Latvia", 139);
CALL upsert_basic_table("countries", "Lebanon", 140);
CALL upsert_basic_table("countries", "Lesotho", 141);
CALL upsert_basic_table("countries", "Liberia", 142);
CALL upsert_basic_table("countries", "Libya", 143);
CALL upsert_basic_table("countries", "Liechtenstein", 144);
CALL upsert_basic_table("countries", "Line Islands", 145);
CALL upsert_basic_table("countries", "Lithuania", 146);
CALL upsert_basic_table("countries", "Luxembourg", 147);
CALL upsert_basic_table("countries", "Macau", 148);
CALL upsert_basic_table("countries", "Madagascar", 149);
CALL upsert_basic_table("countries", "Malawi", 150);
CALL upsert_basic_table("countries", "Malaysia", 151);
CALL upsert_basic_table("countries", "Maldives", 152);
CALL upsert_basic_table("countries", "Mali", 153);
CALL upsert_basic_table("countries", "Malta", 154);
CALL upsert_basic_table("countries", "Marshall Islands", 155);
CALL upsert_basic_table("countries", "Martinique", 156);
CALL upsert_basic_table("countries", "Mauritania", 157);
CALL upsert_basic_table("countries", "Mauritius", 158);
CALL upsert_basic_table("countries", "Mayotte", 159);
CALL upsert_basic_table("countries", "Mediterranean Sea", 160);
CALL upsert_basic_table("countries", "Mexico", 161);
CALL upsert_basic_table("countries", "Micronesia", 162);
CALL upsert_basic_table("countries", "Midway Islands", 163);
CALL upsert_basic_table("countries", "Moldova", 164);
CALL upsert_basic_table("countries", "Monaco", 165);
CALL upsert_basic_table("countries", "Mongolia", 166);
CALL upsert_basic_table("countries", "Montenegro", 167);
CALL upsert_basic_table("countries", "Montserrat", 168);
CALL upsert_basic_table("countries", "Morocco", 169);
CALL upsert_basic_table("countries", "Mozambique", 170);
CALL upsert_basic_table("countries", "Myanmar", 171);
CALL upsert_basic_table("countries", "Namibia", 172);
CALL upsert_basic_table("countries", "Nauru", 173);
CALL upsert_basic_table("countries", "Navassa Island", 174);
CALL upsert_basic_table("countries", "Nepal", 175);
CALL upsert_basic_table("countries", "Netherlands", 176);
CALL upsert_basic_table("countries", "New Caledonia", 177);
CALL upsert_basic_table("countries", "New Zealand", 178);
CALL upsert_basic_table("countries", "Nicaragua", 179);
CALL upsert_basic_table("countries", "Niger", 180);
CALL upsert_basic_table("countries", "Nigeria", 181);
CALL upsert_basic_table("countries", "Niue", 182);
CALL upsert_basic_table("countries", "Norfolk Island", 183);
CALL upsert_basic_table("countries", "North Korea", 184);
CALL upsert_basic_table("countries", "North Macedonia", 185);
CALL upsert_basic_table("countries", "North Sea", 186);
CALL upsert_basic_table("countries", "Northern Mariana Islands", 187);
CALL upsert_basic_table("countries", "Norway", 188);
CALL upsert_basic_table("countries", "Oman", 189);
CALL upsert_basic_table("countries", "Pacific Ocean", 190);
CALL upsert_basic_table("countries", "Pakistan", 191);
CALL upsert_basic_table("countries", "Palau", 192);
CALL upsert_basic_table("countries", "Palmyra Atoll", 193);
CALL upsert_basic_table("countries", "Panama", 194);
CALL upsert_basic_table("countries", "Papua New Guinea", 195);
CALL upsert_basic_table("countries", "Paracel Islands", 196);
CALL upsert_basic_table("countries", "Paraguay", 197);
CALL upsert_basic_table("countries", "Peru", 198);
CALL upsert_basic_table("countries", "Philippines", 199);
CALL upsert_basic_table("countries", "Pitcairn Islands", 200);
CALL upsert_basic_table("countries", "Poland", 201);
CALL upsert_basic_table("countries", "Portugal", 202);
CALL upsert_basic_table("countries", "Puerto Rico", 203);
CALL upsert_basic_table("countries", "Qatar", 204);
CALL upsert_basic_table("countries", "Republic of the Congo", 205);
CALL upsert_basic_table("countries", "Reunion", 206);
CALL upsert_basic_table("countries", "Romania", 207);
CALL upsert_basic_table("countries", "Ross Sea", 208);
CALL upsert_basic_table("countries", "Russia", 209);
CALL upsert_basic_table("countries", "Rwanda", 210);
CALL upsert_basic_table("countries", "Saint Helena", 211);
CALL upsert_basic_table("countries", "Saint Kitts and Nevis", 212);
CALL upsert_basic_table("countries", "Saint Lucia", 213);
CALL upsert_basic_table("countries", "Saint Pierre and Miquelon", 214);
CALL upsert_basic_table("countries", "Saint Vincent and the Grenadines", 215);
CALL upsert_basic_table("countries", "Samoa", 216);
CALL upsert_basic_table("countries", "San Marino", 217);
CALL upsert_basic_table("countries", "Sao Tome and Principe", 218);
CALL upsert_basic_table("countries", "Saudi Arabia", 219);
CALL upsert_basic_table("countries", "Senegal", 220);
CALL upsert_basic_table("countries", "Serbia", 221);
CALL upsert_basic_table("countries", "Seychelles", 222);
CALL upsert_basic_table("countries", "Sierra Leone", 223);
CALL upsert_basic_table("countries", "Singapore", 224);
CALL upsert_basic_table("countries", "Sint Maarten", 225);
CALL upsert_basic_table("countries", "Slovakia", 226);
CALL upsert_basic_table("countries", "Slovenia", 227);
CALL upsert_basic_table("countries", "Solomon Islands", 228);
CALL upsert_basic_table("countries", "Somalia", 229);
CALL upsert_basic_table("countries", "South Africa", 230);
CALL upsert_basic_table("countries", "South Georgia and the South Sandwich Islands", 231);
CALL upsert_basic_table("countries", "South Korea", 232);
CALL upsert_basic_table("countries", "South Sudan", 233);
CALL upsert_basic_table("countries", "Southern Ocean", 234);
CALL upsert_basic_table("countries", "Spain", 235);
CALL upsert_basic_table("countries", "Spratly Islands", 236);
CALL upsert_basic_table("countries", "Sri Lanka", 237);
CALL upsert_basic_table("countries", "State of Palestine", 238);
CALL upsert_basic_table("countries", "Sudan", 239);
CALL upsert_basic_table("countries", "Suriname", 240);
CALL upsert_basic_table("countries", "Svalbard", 241);
CALL upsert_basic_table("countries", "Sweden", 242);
CALL upsert_basic_table("countries", "Switzerland", 243);
CALL upsert_basic_table("countries", "Syria", 244);
CALL upsert_basic_table("countries", "Taiwan", 245);
CALL upsert_basic_table("countries", "Tajikistan", 246);
CALL upsert_basic_table("countries", "Tanzania", 247);
CALL upsert_basic_table("countries", "Tasman Sea", 248);
CALL upsert_basic_table("countries", "Thailand", 249);
CALL upsert_basic_table("countries", "Timor-Leste", 250);
CALL upsert_basic_table("countries", "Togo", 251);
CALL upsert_basic_table("countries", "Tokelau", 252);
CALL upsert_basic_table("countries", "Tonga", 253);
CALL upsert_basic_table("countries", "Trinidad and Tobago", 254);
CALL upsert_basic_table("countries", "Tromelin Island", 255);
CALL upsert_basic_table("countries", "Tunisia", 256);
CALL upsert_basic_table("countries", "Turkey", 257);
CALL upsert_basic_table("countries", "Turkmenistan", 258);
CALL upsert_basic_table("countries", "Turks and Caicos Islands", 259);
CALL upsert_basic_table("countries", "Tuvalu", 260);
CALL upsert_basic_table("countries", "USA", 261);
CALL upsert_basic_table("countries", "Uganda", 262);
CALL upsert_basic_table("countries", "Ukraine", 263);
CALL upsert_basic_table("countries", "United Arab Emirates", 264);
CALL upsert_basic_table("countries", "United Kingdom", 265);
CALL upsert_basic_table("countries", "Uruguay", 266);
CALL upsert_basic_table("countries", "Uzbekistan", 267);
CALL upsert_basic_table("countries", "Vanuatu", 268);
CALL upsert_basic_table("countries", "Venezuela", 269);
CALL upsert_basic_table("countries", "Viet Nam", 270);
CALL upsert_basic_table("countries", "Virgin Islands", 271);
CALL upsert_basic_table("countries", "Wake Island", 272);
CALL upsert_basic_table("countries", "Wallis and Futuna", 273);
CALL upsert_basic_table("countries", "West Bank", 274);
CALL upsert_basic_table("countries", "Western Sahara", 275);
CALL upsert_basic_table("countries", "Yemen", 276);
CALL upsert_basic_table("countries", "Zambia", 277);
CALL upsert_basic_table("countries", "Zimbabwe", 278);
