CALL upsert_basic_table("countries", "Afghanistan", 1);
CALL upsert_basic_table("countries", "Albania", 2);
CALL upsert_basic_table("countries", "Algeria", 3);
CALL upsert_basic_table("countries", "American Samoa", 4);
CALL upsert_basic_table("countries", "Andorra", 5);
CALL upsert_basic_table("countries", "Angola", 6);
CALL upsert_basic_table("countries", "Anguilla", 7);
CALL upsert_basic_table("countries", "Antarctica", 8);
CALL upsert_basic_table("countries", "Antigua And Barbuda", 9);
CALL upsert_basic_table("countries", "Argentina", 10);
CALL upsert_basic_table("countries", "Armenia", 11);
CALL upsert_basic_table("countries", "Aruba", 12);
CALL upsert_basic_table("countries", "Australia", 13);
CALL upsert_basic_table("countries", "Austria", 14);
CALL upsert_basic_table("countries", "Azerbaijan", 15);
CALL upsert_basic_table("countries", "Bahamas", 16);
CALL upsert_basic_table("countries", "Bahrain", 17);
CALL upsert_basic_table("countries", "Bangladesh", 18);
CALL upsert_basic_table("countries", "Barbados", 19);
CALL upsert_basic_table("countries", "Belarus", 20);
CALL upsert_basic_table("countries", "Belgium", 21);
CALL upsert_basic_table("countries", "Belize", 22);
CALL upsert_basic_table("countries", "Benin", 23);
CALL upsert_basic_table("countries", "Bermuda", 24);
CALL upsert_basic_table("countries", "Bhutan", 25);
CALL upsert_basic_table("countries", "Bolivia", 26);
CALL upsert_basic_table("countries", "Bosnia And Herzegovina", 27);
CALL upsert_basic_table("countries", "Botswana", 28);
CALL upsert_basic_table("countries", "Bouvet Island", 29);
CALL upsert_basic_table("countries", "Brazil", 30);
CALL upsert_basic_table("countries", "British Indian Ocean Territory", 31);
CALL upsert_basic_table("countries", "Brunei Darussalam", 32);
CALL upsert_basic_table("countries", "Bulgaria", 33);
CALL upsert_basic_table("countries", "Burkina Faso", 34);
CALL upsert_basic_table("countries", "Burundi", 35);
CALL upsert_basic_table("countries", "Cambodia", 36);
CALL upsert_basic_table("countries", "Cameroon", 37);
CALL upsert_basic_table("countries", "Canada", 38);
CALL upsert_basic_table("countries", "Cape Verde", 39);
CALL upsert_basic_table("countries", "Cayman Islands", 40);
CALL upsert_basic_table("countries", "Central African Republic", 41);
CALL upsert_basic_table("countries", "Chad", 42);
CALL upsert_basic_table("countries", "Chile", 43);
CALL upsert_basic_table("countries", "China", 44);
CALL upsert_basic_table("countries", "Christmas Island", 45);
CALL upsert_basic_table("countries", "Cocos (keeling) Islands", 46);
CALL upsert_basic_table("countries", "Colombia", 47);
CALL upsert_basic_table("countries", "Comoros", 48);
CALL upsert_basic_table("countries", "Congo", 49);
CALL upsert_basic_table("countries", "Congo, The Democratic Republic Of The", 50);
CALL upsert_basic_table("countries", "Cook Islands", 51);
CALL upsert_basic_table("countries", "Costa Rica", 52);
CALL upsert_basic_table("countries", "Cote D'ivoire", 53);
CALL upsert_basic_table("countries", "Croatia", 54);
CALL upsert_basic_table("countries", "Cuba", 55);
CALL upsert_basic_table("countries", "Cyprus", 56);
CALL upsert_basic_table("countries", "Czech Republic", 57);
CALL upsert_basic_table("countries", "Denmark", 58);
CALL upsert_basic_table("countries", "Djibouti", 59);
CALL upsert_basic_table("countries", "Dominica", 60);
CALL upsert_basic_table("countries", "Dominican Republic", 61);
CALL upsert_basic_table("countries", "East Timor", 62);
CALL upsert_basic_table("countries", "Ecuador", 63);
CALL upsert_basic_table("countries", "Egypt", 64);
CALL upsert_basic_table("countries", "El Salvador", 65);
CALL upsert_basic_table("countries", "Equatorial Guinea", 66);
CALL upsert_basic_table("countries", "Eritrea", 67);
CALL upsert_basic_table("countries", "Estonia", 68);
CALL upsert_basic_table("countries", "Ethiopia", 69);
CALL upsert_basic_table("countries", "Falkland Islands (malvinas)", 70);
CALL upsert_basic_table("countries", "Faroe Islands", 71);
CALL upsert_basic_table("countries", "Fiji", 72);
CALL upsert_basic_table("countries", "Finland", 73);
CALL upsert_basic_table("countries", "France", 74);
CALL upsert_basic_table("countries", "French Guiana", 75);
CALL upsert_basic_table("countries", "French Polynesia", 76);
CALL upsert_basic_table("countries", "French Southern Territories", 77);
CALL upsert_basic_table("countries", "Gabon", 78);
CALL upsert_basic_table("countries", "Gambia", 79);
CALL upsert_basic_table("countries", "Georgia", 80);
CALL upsert_basic_table("countries", "Germany", 81);
CALL upsert_basic_table("countries", "Ghana", 82);
CALL upsert_basic_table("countries", "Gibraltar", 83);
CALL upsert_basic_table("countries", "Greece", 84);
CALL upsert_basic_table("countries", "Greenland", 85);
CALL upsert_basic_table("countries", "Grenada", 86);
CALL upsert_basic_table("countries", "Guadeloupe", 87);
CALL upsert_basic_table("countries", "Guam", 88);
CALL upsert_basic_table("countries", "Guatemala", 89);
CALL upsert_basic_table("countries", "Guinea", 90);
CALL upsert_basic_table("countries", "Guinea-bissau", 91);
CALL upsert_basic_table("countries", "Guyana", 92);
CALL upsert_basic_table("countries", "Haiti", 93);
CALL upsert_basic_table("countries", "Heard Island And Mcdonald Islands", 94);
CALL upsert_basic_table("countries", "Holy See (vatican City State)", 95);
CALL upsert_basic_table("countries", "Honduras", 96);
CALL upsert_basic_table("countries", "Hong Kong", 97);
CALL upsert_basic_table("countries", "Hungary", 98);
CALL upsert_basic_table("countries", "Iceland", 99);
CALL upsert_basic_table("countries", "India", 100);
CALL upsert_basic_table("countries", "Indonesia", 101);
CALL upsert_basic_table("countries", "Iran, Islamic Republic Of", 102);
CALL upsert_basic_table("countries", "Iraq", 103);
CALL upsert_basic_table("countries", "Ireland", 104);
CALL upsert_basic_table("countries", "Israel", 105);
CALL upsert_basic_table("countries", "Italy", 106);
CALL upsert_basic_table("countries", "Jamaica", 107);
CALL upsert_basic_table("countries", "Japan", 108);
CALL upsert_basic_table("countries", "Jordan", 109);
CALL upsert_basic_table("countries", "Kazakstan", 110);
CALL upsert_basic_table("countries", "Kenya", 111);
CALL upsert_basic_table("countries", "Kiribati", 112);
CALL upsert_basic_table("countries", "Korea, Democratic People's Republic Of", 113);
CALL upsert_basic_table("countries", "Korea, Republic Of", 114);
CALL upsert_basic_table("countries", "Kosovo", 115);
CALL upsert_basic_table("countries", "Kuwait", 116);
CALL upsert_basic_table("countries", "Kyrgyzstan", 117);
CALL upsert_basic_table("countries", "Lao People's Democratic Republic", 118);
CALL upsert_basic_table("countries", "Latvia", 119);
CALL upsert_basic_table("countries", "Lebanon", 120);
CALL upsert_basic_table("countries", "Lesotho", 121);
CALL upsert_basic_table("countries", "Liberia", 122);
CALL upsert_basic_table("countries", "Libyan Arab Jamahiriya", 123);
CALL upsert_basic_table("countries", "Liechtenstein", 124);
CALL upsert_basic_table("countries", "Lithuania", 125);
CALL upsert_basic_table("countries", "Luxembourg", 126);
CALL upsert_basic_table("countries", "Macau", 127);
CALL upsert_basic_table("countries", "Macedonia, The Former Yugoslav Republic Of", 128);
CALL upsert_basic_table("countries", "Madagascar", 129);
CALL upsert_basic_table("countries", "Malawi", 130);
CALL upsert_basic_table("countries", "Malaysia", 131);
CALL upsert_basic_table("countries", "Maldives", 132);
CALL upsert_basic_table("countries", "Mali", 133);
CALL upsert_basic_table("countries", "Malta", 134);
CALL upsert_basic_table("countries", "Marshall Islands", 135);
CALL upsert_basic_table("countries", "Martinique", 136);
CALL upsert_basic_table("countries", "Mauritania", 137);
CALL upsert_basic_table("countries", "Mauritius", 138);
CALL upsert_basic_table("countries", "Mayotte", 139);
CALL upsert_basic_table("countries", "Mexico", 140);
CALL upsert_basic_table("countries", "Micronesia, Federated States Of", 141);
CALL upsert_basic_table("countries", "Moldova, Republic Of", 142);
CALL upsert_basic_table("countries", "Monaco", 143);
CALL upsert_basic_table("countries", "Mongolia", 144);
CALL upsert_basic_table("countries", "Montserrat", 145);
CALL upsert_basic_table("countries", "Montenegro", 146);
CALL upsert_basic_table("countries", "Morocco", 147);
CALL upsert_basic_table("countries", "Mozambique", 148);
CALL upsert_basic_table("countries", "Myanmar", 149);
CALL upsert_basic_table("countries", "Namibia", 150);
CALL upsert_basic_table("countries", "Nauru", 151);
CALL upsert_basic_table("countries", "Nepal", 152);
CALL upsert_basic_table("countries", "Netherlands", 153);
CALL upsert_basic_table("countries", "Netherlands Antilles", 154);
CALL upsert_basic_table("countries", "New Caledonia", 155);
CALL upsert_basic_table("countries", "New Zealand", 156);
CALL upsert_basic_table("countries", "Nicaragua", 157);
CALL upsert_basic_table("countries", "Niger", 158);
CALL upsert_basic_table("countries", "Nigeria", 159);
CALL upsert_basic_table("countries", "Niue", 160);
CALL upsert_basic_table("countries", "Norfolk Island", 161);
CALL upsert_basic_table("countries", "Northern Mariana Islands", 162);
CALL upsert_basic_table("countries", "Norway", 163);
CALL upsert_basic_table("countries", "Oman", 164);
CALL upsert_basic_table("countries", "Pakistan", 165);
CALL upsert_basic_table("countries", "Palau", 166);
CALL upsert_basic_table("countries", "Palestinian Territory, Occupied", 167);
CALL upsert_basic_table("countries", "Panama", 168);
CALL upsert_basic_table("countries", "Papua New Guinea", 169);
CALL upsert_basic_table("countries", "Paraguay", 170);
CALL upsert_basic_table("countries", "Peru", 171);
CALL upsert_basic_table("countries", "Philippines", 172);
CALL upsert_basic_table("countries", "Pitcairn", 173);
CALL upsert_basic_table("countries", "Poland", 174);
CALL upsert_basic_table("countries", "Portugal", 175);
CALL upsert_basic_table("countries", "Puerto Rico", 176);
CALL upsert_basic_table("countries", "Qatar", 177);
CALL upsert_basic_table("countries", "Reunion", 178);
CALL upsert_basic_table("countries", "Romania", 179);
CALL upsert_basic_table("countries", "Russian Federation", 180);
CALL upsert_basic_table("countries", "Rwanda", 181);
CALL upsert_basic_table("countries", "Saint Helena", 182);
CALL upsert_basic_table("countries", "Saint Kitts And Nevis", 183);
CALL upsert_basic_table("countries", "Saint Lucia", 184);
CALL upsert_basic_table("countries", "Saint Pierre And Miquelon", 185);
CALL upsert_basic_table("countries", "Saint Vincent And The Grenadines", 186);
CALL upsert_basic_table("countries", "Samoa", 187);
CALL upsert_basic_table("countries", "San Marino", 188);
CALL upsert_basic_table("countries", "Sao Tome And Principe", 189);
CALL upsert_basic_table("countries", "Saudi Arabia", 190);
CALL upsert_basic_table("countries", "Senegal", 191);
CALL upsert_basic_table("countries", "Serbia", 192);
CALL upsert_basic_table("countries", "Seychelles", 193);
CALL upsert_basic_table("countries", "Sierra Leone", 194);
CALL upsert_basic_table("countries", "Singapore", 195);
CALL upsert_basic_table("countries", "Slovakia", 196);
CALL upsert_basic_table("countries", "Slovenia", 197);
CALL upsert_basic_table("countries", "Solomon Islands", 198);
CALL upsert_basic_table("countries", "Somalia", 199);
CALL upsert_basic_table("countries", "South Africa", 200);
CALL upsert_basic_table("countries", "South Georgia And The South Sandwich Islands", 201);
CALL upsert_basic_table("countries", "Spain", 202);
CALL upsert_basic_table("countries", "Sri Lanka", 203);
CALL upsert_basic_table("countries", "Sudan", 204);
CALL upsert_basic_table("countries", "Suriname", 205);
CALL upsert_basic_table("countries", "Svalbard And Jan Mayen", 206);
CALL upsert_basic_table("countries", "Swaziland", 207);
CALL upsert_basic_table("countries", "Sweden", 208);
CALL upsert_basic_table("countries", "Switzerland", 209);
CALL upsert_basic_table("countries", "Syrian Arab Republic", 210);
CALL upsert_basic_table("countries", "Taiwan, Province Of China", 211);
CALL upsert_basic_table("countries", "Tajikistan", 212);
CALL upsert_basic_table("countries", "Tanzania, United Republic Of", 213);
CALL upsert_basic_table("countries", "Thailand", 214);
CALL upsert_basic_table("countries", "Togo", 215);
CALL upsert_basic_table("countries", "Tokelau", 216);
CALL upsert_basic_table("countries", "Tonga", 217);
CALL upsert_basic_table("countries", "Trinidad And Tobago", 218);
CALL upsert_basic_table("countries", "Tunisia", 219);
CALL upsert_basic_table("countries", "Turkey", 220);
CALL upsert_basic_table("countries", "Turkmenistan", 221);
CALL upsert_basic_table("countries", "Turks And Caicos Islands", 222);
CALL upsert_basic_table("countries", "Tuvalu", 223);
CALL upsert_basic_table("countries", "Uganda", 224);
CALL upsert_basic_table("countries", "Ukraine", 225);
CALL upsert_basic_table("countries", "United Arab Emirates", 226);
CALL upsert_basic_table("countries", "United Kingdom", 227);
CALL upsert_basic_table("countries", "United States", 228);
CALL upsert_basic_table("countries", "United States Minor Outlying Islands", 229);
CALL upsert_basic_table("countries", "Uruguay", 230);
CALL upsert_basic_table("countries", "Uzbekistan", 231);
CALL upsert_basic_table("countries", "Vanuatu", 232);
CALL upsert_basic_table("countries", "Venezuela", 233);
CALL upsert_basic_table("countries", "Viet Nam", 234);
CALL upsert_basic_table("countries", "Virgin Islands, British", 235);
CALL upsert_basic_table("countries", "Virgin Islands, U.s.", 236);
CALL upsert_basic_table("countries", "Wallis And Futuna", 237);
CALL upsert_basic_table("countries", "Western Sahara", 238);
CALL upsert_basic_table("countries", "Yemen", 239);
CALL upsert_basic_table("countries", "Zambia", 240);
CALL upsert_basic_table("countries", "Zimbabwe", 241);
